### PR TITLE
Drop ImageMagick and update submodules

### PR DESCRIPTION
**Pull request by buccalon**
Issue: #14 
- Drop ImageMagick for libvips
- Upgrade to Omeka-S 3.0.2
- Update and replace some submodules

@davidheyman let me know if you want to test this against our database before deploying it

### CODE REVIEW

**Comment by buccalon** [comment]
https://github.com/Daniel-KM/Omeka-S-module-ImageServer#vips-as-default-thumbnailer

**Comment by davidheyman** [comment]
@buccalon I've put it online at https://beta.images.imaginerio.org/s/imaginerio/page/welcome but the IIIF manifests are failing. Can you take a look at how things are configured in the admin panel?

Ideally any changes you make would be able to be brought back into the code, but I understand that might not be a possibility.

**Comment by buccalon** [comment]
@davidheyman Thanks for setting this up. I broke the admin panel when upgrading the [Clean URL module](https://github.com/Daniel-KM/Omeka-S-module-CleanUrl), and I can't access the logs. If you delete this module in the database (module column), it will work again. In my understanding, this is caused because the module is not handling the file `cleanurl.config.php` in the upgrade process:

> IMPORTANT: The module copies one file in the main config directory of Omeka, "cleanurl.config.php". this is a list of all reserved words for the first level of the url, when there are no site and page prefixes. All common routes are included. It is larger than needed in order to manage future modules or improvments, according to existing modules in Omeka classic or Omeka S or common wishes. Furthermore, it contains the list of site slugs and some other settings in order to manage routing quickly, in particular when there are no site and page paths. Contrary to a previous version, this file is automatically updated and should not be updated manually.

Of course, we could patch something in the docker setup, but this seems not adequate.

@Daniel-KM can you confirm if we are doing something wrong here, please?

---

Additionally, if I try to locally upload a file I run into the permission issue that affects files created by the docker user:

image

@davidheyman Let me know if there is anything I can set up in my environment to fix this problem. I read about matching the user ID with the Docker ID, but I hope there is a better way to handle volume permissions in the docker-compose file. Currently I use chmod in the files directory everytime I clone the repo.

**Comment by Daniel-KM** [comment]
For CleanUrl, the copy of the original file is required to bypass the original routes when the main slug is removed. So it should be managed by the box.

**Pull request closed without merging**
