### PR TITLE
Omeka-S v3.0.1

### PR DESCRIPTION
**Pull request by buccalon**
To update our deployment we need Omeka-s 3.0.1 working with IIIF v3.

This updates omeka.sql with new resource templates and item-set configs.

Know issues:
- Performance with IIIF collections v3 (slow)

Development environment:
- https://v3.imaginerio.org/

### CODE REVIEW

**Comment by Daniel-KM** [comment]
Note that the config form was improved a second time, but still understandable. It allows now to have url with ark + a specific property for the file.

**Comment by Daniel-KM** [comment]
I fixed the issue [ImageServer#3](https://github.com/Daniel-KM/Omeka-S-module-ImageServer/issues/3) on ImageServer and many more. 

I included a big improvement on ImageServer too: the tiles are now built by default for all files, so the media type "tile" is no more needed.

**Comment by Daniel-KM** [comment]
Various fixes and new improvements: there is an option to tile automatically or not (not to be used when existing are not tiled); jobs are managed better (by item), and vips is supported, so tiling and dynamic requests are a lot quicker.

**Comment by buccalon** [comment]
@Daniel-KM do we need to change our dockerfile to support vips?

**Comment by Daniel-KM** [comment]
For local resquests only with openseadragon/uv/mirador, or when the images are lower than 10 MB, there is no difference, since the pre-tiled files are served instantly. If you have a small server, the speed improvement is visible. If you have people who do zoning or ask for special regions via iiif urls, the difference is visible too. See https://github.com/libvips/libvips/wiki/Speed-and-memory-use. So I'm installing it on servers I maintain, even if the module is fresh.

**Comment by davidheyman** [comment]
@buccalon I've just deployed v3 at https://images.imaginerio.org. Can you run it through some quick tests to make sure everything is working as it should?

**Comment by buccalon** [comment]
@davidheyman
I've updated the submodules and tested tilling images with libvips on localhost.
About the deployment, not sure why is still running v2.1.2 with the old modules.

Screenshot from 2020-12-05 15-20-38

You can check that at https://images.imaginerio.org/admin/system-info

**Comment by davidheyman** [comment]
@buccalon Can you take a look at the commit that the cleanUrl module is using? It doesn't exist any more and it's causing problems trying to update the other submodules.

**Comment by buccalon** [comment]
@davidheyman Something annoying. Just removed and added again. Let me know if it works.

**Comment by buccalon** [comment]
@Daniel-KM we are facing timeout only with IIIF v3. Any idea of what might be the issue?

Screenshot from 2020-12-07 16-48-14

- https://images.imaginerio.org/iiif/0071824cx070-11
- https://images.imaginerio.org/iiif/collection/all

**Comment by Daniel-KM** [comment]
I improved a lot process for items, but not for collection. How many items or medias have your collection?

**Comment by Daniel-KM** [comment]
And last version of ImageServer is Daniel-KM/Omeka-S-module-ImageServer@4c63b00

**Comment by buccalon** [comment]
@Daniel-KM

Submodules are pointed to the correct heads now, the problem was a conflicting local commit on CleanUrl.

Our collection has 1.561 items, with 1 media each. This number will be 10.000 in the near future.

**Comment by buccalon** [comment]
Everything working on https://v3.imaginerio.org/

@davidheyman can we use Nginx to cache the manifests, so large collections don't take too long?

About large JSON files:
- https://joshzeigler.com/technology/web-development/how-big-is-too-big-for-json

**Pull request merged**
